### ISSUE TITLE
Update shortText for patient.deceased 

### ISSUE THREAD

**Issue by medcomire** [hl7dk/dk-medcom#109]
Please add a description that if only patient is deceased the flag deceased shall be sent even the fact that the deceaced flag is must support

**Comment by MedComAnders** [comment]
If posiable create constrains only true. never false.

**Comment by tmh-mjolner** [comment]
> If posiable create constrains only true. never false.

It is normally allowed to set it to false even though it means the same as if the value is not set

**Comment by MedComAnders** [comment]
Has been fixed in #191
