### ISSUE TITLE
Overview-advis codes - on-leave -> onleave

### ISSUE THREAD

**Issue by MedComAnders** [hl7dk/dk-medcom#125]
http://build.fhir.org/ig/hl7dk/dk-medcom/hospitalnotification/pdf/Overview_advis_codes_HL7_FHIR.pdf
on-leave has to be changed to onleave according to  
http://build.fhir.org/ig/hl7dk/dk-medcom/ValueSet-medcom-hospitalNotification-encounterStatus.html

**Comment by tmsMedcom** [comment]
![image](https://user-images.githubusercontent.com/88831880/140474864-4a6c3626-58d0-47b7-aa6f-401ab23f436a.png)
![image](https://user-images.githubusercontent.com/88831880/140474891-b327ff54-0e91-49c8-aef7-0e2770a31e0f.png)
Hvilket at billederne er korrekt?

**Comment by MedComAnders** [comment]
Jeg er gået uf fra at det er den første. der er daterede til 3. marts. har du en kilde til billede nr. to?

**Comment by tmsMedcom** [comment]
Billede to har jeg baseret på følgende kodesystem: https://build.fhir.org/ig/hl7dk/dk-medcom/branches/1.0.4-release-candidate/CodeSystem-medcom-messaging-activityCodes.html

**Comment by tmsMedcom** [comment]
@ovi-medcom hvad tænker du er korrekt af ovenstående muligheder?

**Comment by tmsMedcom** [comment]
Det første billede er korrekt. Ændrer dog "any activity" til "Current activity" og tilføj følgende tekst til dokumentet: 
"Identificering af om en patient er død, sker på baggrund af elementet Patient.deceased er sat til 'true'."
""current activity" angiver, at aktiviteten fra den forrige besked skal angives. Eksempelvis, hvis en patient dør under indlæggelse skal den Provenance.activity være 'admit-inpatient' og dør en patient under orlov, skal Provenance.activity være 'start-leave-inpatient'."
""current status" angiver, at statussen fra den forrige besked skal angives. Eksempelvis, hvis Encounter.status var 'onleave' inden statussen blev ændret til 'finished' skal den igen ændres tilbage til 'onleave'.

**Comment by tmsMedcom** [comment]
See #195
