### ISSUE TITLE
TouchStone - Opdele testscripts, så de matcher use cases og bindes sammen i test suiter

### ISSUE THREAD

**Issue by ovi-medcom** [hl7dk/dk-medcom#134]
Kombiner testscripts i testsuiter og binde dem sammen ved at registrere en Communication ressource på HAPI-FHIR, som er vores husholdning over hvad der er sket i meddelelsesudvekslingen på tværs af testscripts.

**Comment by tmsMedcom** [comment]
Illustration af ovenstående ses her: 
![TestSetUp-HopistalNotification](https://user-images.githubusercontent.com/88831880/130065822-b1038c39-ab4f-4cd4-927b-ca24c1354401.jpg)

**Comment by tmsMedcom** [comment]
Handled elsewhere
