### ISSUE TITLE
medcomfhir.dk virker ikke

### ISSUE THREAD

**Issue by tmsMedcom** [hl7dk/dk-medcom#137]
I dokumentationen for HospitalNotification er følgende sider/dokumenter identificeret med links til medcomfhir.dk, der ikke fungerer:
- http://build.fhir.org/ig/hl7dk/dk-medcom/StructureDefinition-medcom-hospitalNotification-message.html 
- http://build.fhir.org/ig/hl7dk/dk-medcom/Bundle-eada5e7a-a7ef-43b1-bfd6-024d5e64294c.html
- https://build.fhir.org/ig/hl7dk/dk-medcom/StructureDefinition-medcom-hospitalNotification-encounter.html
- https://github.com/hl7dk/dk-medcom/blob/master/doc/message/HospitalNotification/TestProtocols/HospitalNotification_afsendelse_1.0_300621.docx
- https://github.com/hl7dk/dk-medcom/blob/master/doc/message/HospitalNotification/TestProtocols/HospitalNotification_modtagelse_1.0_300621.docx

**Comment by MedComAnders** [comment]
all links are active. 
they are dependinding on fhir.medcom.dk
