### ISSUE TITLE
Invalid examples on acknowledgement message

### ISSUE THREAD

**Issue by tmh-mjolner** [hl7dk/dk-medcom#145]

**Comment by MedComAnders** [comment]
What to do: 
Needs provenance in the exampels. 
code from #152  needs to be added

**Comment by MedComAnders** [comment]
waiting for branche https://github.com/hl7dk/dk-medcom/tree/1.0.3-ACK-VANSEnvCodes to be comitted before this can build.

**Comment by MedComAnders** [comment]
Fixed in #199
