### ISSUE TITLE
Provenance.entity.role

### ISSUE THREAD

**Issue by MedComAnders** [hl7dk/dk-medcom#158]
The shall always be derivation.
Needs to be described in the IG, examples and http://build.fhir.org/ig/hl7dk/dk-medcom/hospitalnotification/HospitalNotificationAdmitOnleaveFinishedExample.png

**Comment by tmsMedcom** [comment]
The following has been decided to be valid for use of Provenance: 
entity.role: How an entity was used in this activity. When the message is the first in a thread, the role shall be 'source', when a message is a response, a correction or a forwarding message the role shall be 'revision' and when the message is a cancelation the role shall be 'removal'.

**Comment by tmsMedcom** [comment]
See pull request #190
