### ISSUE TITLE
Provenance.activity.coding.system

### ISSUE THREAD

**Issue by MedComAnders** [hl7dk/dk-medcom#159]
Provenance.activity.coding.system: Hvilket system skal benyttes her? Vi har fundet dette ValueSet, der er angivet som ’Binding’ (https://build.fhir.org/ig/hl7dk/dk-medcom/branches/1.0/ValueSet-medcom-hospitalNotification-messageActivities.html), som ser ud til at inkludere koderne deceased, revise-deseased og cancel-deseased, men de er ikke en del af det kodesystem, som er angivet som ’Required Pattern’ (https://build.fhir.org/ig/hl7dk/dk-medcom/branches/1.0/CodeSystem-medcom-messaging-activityCodes). Det ser ud til, at ValueSettet kun er angivet som ’Binding’ i profilen for Bundlen, men et andet ValueSet er angivet som ’Binding’ i profilen for Provenance. 

Det er godt set. Det er helt korrekt at koderne omkring ’deceased’ skal med

**Comment by tmsMedcom** [comment]
Has been made - The description concern the codeSystem in branch 1.0, but in the current branch 1.0.3 the codes are included in the codeSystem: http://build.fhir.org/ig/hl7dk/dk-medcom/CodeSystem-medcom-messaging-activityCodes.html
