### ISSUE TITLE
carecomminication examples - correct encounter to Core

### ISSUE THREAD

**Issue by MedComAnders** [hl7dk/dk-medcom#160]
All carecomminication examples shall be encounter Core and not lpr3.
--------------------------
Encounter.serviceProvider er angivet i mapningsdokumentet til at være stedet til både information om afsender og modtager – det giver ikke helt mening for mig? I eksemplet og profilerne ser det ud til at være i MessageHeader.sender og .destination. Hvad skal serviceProvider bruges til (hvis noget, for det er ikke mustSupport)? 

Det er ikke korrekt angivet i mapningsdokumentet og at elementerne medcomHospitalNotificationMessageHeader.<destination.primary.reciever/sender>.medcomMessagingOrganization.identifier bruges til at angive afsender og modtager 

serviceProvider angiver blot, at den organisation, der varertager patientens Encounter er med i bundlen. Elementet behøver ikke være udfyldt eller medsendes.

**Comment by tmsMedcom** [comment]
see #217
