### ISSUE TITLE
Add a section on how the communication/transport should be done

### ISSUE THREAD

**Issue by cooperthompson** [hl7dk/dk-medcom#17]
The current IG only documents the payload structure.  There is no information on the transport.  Is the intent to use [$process-message](https://www.hl7.org/fhir/messaging.html#process)?  What is the security layer?  [SMART Backend Services](http://build.fhir.org/ig/HL7/bulk-data-export/authorization/index.html)?

If this IG does not intend to use any of the FHIR transport or security layers, and only use the FHIR payload, even that would be useful to document in this IG, with a reference to wherever the transport/security specifications are (e.g. if the MedCom/XML or MedCom/EDIFACT transports are being re-used).

**Comment by medcomire** [comment]
In description is done in danish - but we do no yet have a English version, the issue stays open.
For the danish version please refer to https://github.com/hl7dk/dk-medcom/raw/master/input/images/pdf/MedComs_FHIR-meddelelser_og_forsendelseskuvert_1.0.pdf

**Comment by tmsMedcom** [comment]
The English description is made: https://github.com/hl7dk/dk-medcom/raw/master/input/images/pdf/MedCom_FHIR-messages_and_enclosing_envelope.pdf
