### ISSUE TITLE
Generating Java source code based on the dk-medcom definitions

### ISSUE THREAD

**Issue by mada4586** [hl7dk/dk-medcom#18]
Hello,

I'm running a pilot implementation of ClinicalEmail and Hospital Notif./Discharge, using the Java HAPI-FHIR suite. Your current profiles get imported into JPA FHIR Server correctly, but I'm missing the possibility to generate Java classes from them. It is possible that this is not supported yet; however, it seems to be possible in the reverse side (from annotated Java classes to XML resources).

Hence goes the question: what source format do you use for creating your profiles? Do you edit them directly as XMLs, or do you use some tooling to support you?

Thank you in advance.

**Comment by medcomire** [comment]
Hi 
Thank you very much for your interest in our profiles. The present release will be replaced next week (ultimo week 40) by an update that we expect will be buildable. The present release is not able to validate and I expect that this is the reason that the java client is not able to build classes. 
 We are using a profiling tool like Forge to create the profiles but are also using the xml editing.   

Kind regards
MedCom

**Comment by medcomire** [comment]
Hi 
The release 0.9 is now master - the problem generating java classes is expected to be solved. Please reopen the issue if not the case @mada4586
