### ISSUE TITLE
Add more descriptive text to elements in MedComMessagingProvenance

### ISSUE THREAD

**Issue by tmsMedcom** [hl7dk/dk-medcom#184]

**Comment by tmsMedcom** [comment]
Add more descriptive text to 'Scope and Usage'

**Comment by tmsMedcom** [comment]
**Notes from discussion about Provenance.:**
target : targets the MedComMessagingMessageHeader from the previous message. 
dateTimeExtension: a human readable date and time for when the message is sent.
instant: a system readable date and time for when the message is sent. 
activity: - 
agent: the actors involved in the activity taking place
agent.who: a reference to the actor, which shall be a MedComMessagingOrganization. If more actors has been involved, the element must occur several times with reference to every actor. [REMOVE BUNDLED {b}!]
entity: - 
entity.role: How an entity was used in this activity. When the message is the first in a thread, the role shall be 'source', when a message is a response, a correction or a forwarding message the role shall be 'revision' and when the message is a cancelation the role shall be 'removal'. 
entity.what: the identity of the previous message. This is a reference to [What is this a reference to for either case??]
entity.what.reference: If the previous message is a FHIR message, this element shall contain the SOR from the sender of the message. This shall be from a MedComMessagingOrganization. 
entity.what.identity: If the previous message is an EDIFACT or OIOXML, this element shall be expressed as [lokationsnummer]#[brevid] from the previous EDIFACT or OIOXML message.

**Comment by ovi-medcom** [comment]
@ovi-medcom test

**Comment by tmsMedcom** [comment]
Handled in #196
