### ISSUE TITLE
LPR3 shall not be mandatory for HospitalNotification

### ISSUE THREAD

**Issue by medcomire** [hl7dk/dk-medcom#29]
Instead a "kontakt-id" shall be used for the encounter and the lpr3 id may be applied

**Comment by tmh-mjolner** [comment]
Skal justeres så kontakt id ikke anvendes, men episode of care id skal være der (udover evt. lpr3 id)

**Comment by tmh-mjolner** [comment]
Episode of care id er nu mandatory med mulighed for LPR2 identifier

**Comment by medcomire** [comment]
Det er forhåbentligt lPR3 (;
