### ISSUE TITLE
Missing examples in the IG of the use of provenance

### ISSUE THREAD

**Issue by medcomire** [hl7dk/dk-medcom#33]
Please add examples for the CareCommunication and HospitalNofication bundle examples for different use of provenance.
For the CareCommunication add bundle examples of message send/receive reply/forward

For the HospitalNotification make a bundle example of patient admit, patient on leave, patient finished leave, patient discharged

**Comment by tmh-mjolner** [comment]
Done for hospital admission - care communication ramaining

**Comment by tmh-mjolner** [comment]
Care communication examples done
