### ISSUE TITLE
Add type to messaging organization identifier

### ISSUE THREAD

**Issue by tmh-mjolner** [hl7dk/dk-medcom#39]
MedComMessagingOrganization organization/identifier skal også have type med som krævet værdi og must support udover system og value. 

<identifier> 
          <type value="SOR"/> 
          <system value="urn:oid:1.2.208.176.1.1"/> 
          <value value="123456789012345"/> 
</identifier> 

<identifier> 
          <type value="EAN"/> 
          <system value="urn:oid: 1.3.88"/> 
          <value value="1234567890123"/> 
</identifier>

**Comment by tmh-mjolner** [comment]
This will make sor identifier differ from dk core. Sure we want that?

**Comment by medcomire** [comment]
The type shall be applied at dk-core level if SOR shall be shown as system type
