### ISSUE TITLE
HospitalNotification: Add flag to indicate that a "report of admission" shall be send 

### ISSUE THREAD

**Issue by medcomire** [hl7dk/dk-medcom#42]
Please a flag to indicate that the receiving municipally unit shall send a report of admission or not

**Comment by medcomire** [comment]
Is MessageHeader the place for such a flag extension ?

Eg. Bundle.medComMessagingMessageHeader.reportOfAdmissionflag

**Comment by ovi-medcom** [comment]
I would start looking in the request element for such a feature

**Comment by tmh-mjolner** [comment]
Request element is only allowed for batch, transaction and history types.
I cannot find any best practice for this, so I think we should put it in the message header.
