### ISSUE TITLE
Create extension to encounter.class ValueSet for CareCommunication

### ISSUE THREAD

**Issue by medcomire** [hl7dk/dk-medcom#47]
The encounter.class has at present a value set that are extensible and the present value set do no contain the possibility to set an "uknown" value.
The task is to extend the CareCommunicationEncounter.class value set with the value "Unknown".

**Comment by tmh-mjolner** [comment]
@medcomire - Den her forstår jeg ikke. CareCommunicationEncounter findes ikke. Er det HospitalNotificationEncounter og hvis det er så fremgår unknown ikke som en mulighed i oversigten over adviskoder?

**Comment by medcomire** [comment]
True, and this is the task - to extend the ValueSet with an "unknown" code. This allows the CareCommunication encounter to have status "unknown" for both class and status.

**Comment by medcomire** [comment]
And yes - the changes will apply to a MedCom Core instance as it is the MedComCoreEncounter that shall be applied this new status flavour. It is true that no MedComCareCommunicationEncounter instance exists
