### ISSUE TITLE
Add Slice to Provenance to reflect authorisation datetime

### ISSUE THREAD

**Issue by medcomire** [hl7dk/dk-medcom#48]
To reflect the actual authorisation date/time for both CareCommunication and HospitalNotification the Provenance.occuredDatTime timestamp shall be sliced to also contain a Provenance.authorisation.timestamp.

**Comment by tmh-mjolner** [comment]
@medcomire - Det kan man ikke. Vi kan lave lave en separat extension til det på provenance, men hvad skal den bruges til og hvorfor skal det være med i historikken på en besked?

**Comment by medcomire** [comment]
Det er for at angive autorisations tidsstempel som er et mandatory felt på vores MedCom oioxml og edifact standarder - vi drøftede dette på et af vores møder og blev enige om at slice occuredTime ..
Autorisations tidsstemplet er det tidspunkt hvor klinikeren sender beskeden videre i systemet...

**Comment by tmh-mjolner** [comment]
Provenance is information about the events on the message. Authorization datetime is when the content is authored by the clinician. This indicates the the datetime on CareCommunication payload is the authorization datetime and authorization datetime does not make much sense for HospitalNotification. The timestamp on the message states when the message was assembled.

Isn't that all we need?
