### ISSUE TITLE
The HospitalNotification Patient shall have a deceased must support

### ISSUE THREAD

**Issue by medcomire** [hl7dk/dk-medcom#54]
As the Patient.deceased is a part of the status handling regarding HospitalNotification the Patient.deceased shall be defined as must support for only the HospitalNotification Patient profile.

**Comment by tmh-mjolner** [comment]
Did not work well to do it for hospital notification. Has added it on patient with a definition that it shall contain information if the patient is deceased and it is relevant in the given context

**Comment by medcomire** [comment]
Are there a default value for deceased or shall we define it or both

**Comment by tmh-mjolner** [comment]
Definition for feltet er følgende: If there's no value in the instance, it means there is no statement on whether or not the individual is deceased. Most systems will interpret the absence of a value as a sign of the person being alive
